### ISSUE TITLE
error upon running "dts challenges evaluate"

### ISSUE THREAD

**Issue by gunshi** [duckietown/challenge-aido_LF-template-ros#1] opened 2018-11-02 20:44 UTC
```
INFO:dts:The server URL is: https://challenges.duckietown.org/v3
INFO:dts:Updating container duckietown/dt-challenges-evaluator:v3
INFO:dts:This might take some time.
ERROR:dts:stopping previous local-evaluator

dts :  Traceback (most recent call last):
    :    File "/home/user1/.local/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
    :      response.raise_for_status()
    :    File "/home/user1/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    :      raise HTTPError(http_error_msg, response=self)
    :  requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/2dd34a60ba2cc8a3263e7b27e3156b5af52c283d300e956bd551bfdc3c68b7d4/stop
    :  
    :  During handling of the above exception, another exception occurred:
    :  
    :  Traceback (most recent call last):
    :    File "/home/user1/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 38, in cli_main
    :      cli_main_()
    :    File "/home/user1/.local/lib/python3.6/site-packages/dt_shell/__init__.py", line 106, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/home/user1/anaconda3/lib/python3.6/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/user1/.local/lib/python3.6/site-packages/dt_shell/cli.py", line 409, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/user1/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    :      cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
    :    File "/home/user1/.local/lib/python3.6/site-packages/dt_shell/dt_command_abs.py", line 52, in do_command
    :      cls.command(shell, args)
    :    File "/home/user1/.dt-shell/commands/challenges/evaluate/command.py", line 160, in command
    :      container.stop()
    :    File "/home/user1/.local/lib/python3.6/site-packages/docker/models/containers.py", line 405, in stop
    :      return self.client.api.stop(self.id, **kwargs)
    :    File "/home/user1/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    :      return f(self, resource_id, *args, **kwargs)
    :    File "/home/user1/.local/lib/python3.6/site-packages/docker/api/container.py", line 1120, in stop
    :      self._raise_for_status(res)
    :    File "/home/user1/.local/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
    :      raise create_api_error_from_http_exception(e)
    :    File "/home/user1/.local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    :      raise cls(e, response=response, explanation=explanation)
    :  docker.errors.APIError: 500 Server Error: Internal Server Error ("cannot stop container: 2dd34a60ba2cc8a3263e7b27e3156b5af52c283d300e956bd551bfdc3c68b7d4: Cannot kill container 2dd34a60ba2cc8a3263e7b27e3156b5af52c283d300e956bd551bfdc3c68b7d4: unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
    :  : unknown")

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  duckietown-shell-commands: 1.0.15
    :  python: "3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) \n[GCC 7.2.0]"

```
Running dts challenges evaluate works successfully on the challenge-aido1_LF1-baseline-duckietown
 repo though.
Thanks

**Comment by liampaull** [comment] 2018-11-04 19:02
I was unable to reproduce this - @AndreaCensi could it just be that the server was down at this error or something ? @gunshi can you try it again ?

**Comment by bhairavmehta95** [comment] 2018-11-05 19:16
Looks like a server issue - closing.

**Closed as completed by bhairavmehta95** 2018-11-05 19:16 UTC

**Comment by gunshi** [comment] 2018-11-05 19:33
Resolved by adding ssh keys.
I was getting stuck at a cloning step (which was because of ssh keys not being added into my github account). However I was earlier suspecting a faulty internet connection, so when i ctrl-c-ed there, and reran the evaluate command, i then got the reported error everytime.
`sudo service docker restart` fixes that.
Thanks.
